#server.port=9090
#server.servlet.encoding.charset=UTF-8
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8


spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username : SPRING
    password : SPRING
    hikari:
      pool-name: ms-pool
      maximum-pool-size: 10
      idle-timeout: 1000000
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        timezone: Asia/Seoul

